### ISSUE TITLE
Simple package manager instructions

### ISSUE THREAD

**Issue by markusbkk** [eltanin-os/glacies#1]
I love this project a ton (it was pretty much love at first sight. Booted into it from Apple UTM and was immediately impressed -- albeit, the Durden defaults need some work and the binding bit was a bit confusing before I decided to just skip it) and intend making it my daily driver/help with its development once I have a new x86 based laptop.

That being said, I'd love some brief documentation on how package management is supposed to work.

For instance, how do I install `git`? Is there already a remote repository prepared for it somewhere? Do I need to update Arbor and add it there myself? Will the final version maybe include some sort of compatibility shim for apt repositories?

**Comment by markusbkk** [comment]
I'd actually be interested to learn more about the overall culture on EltaninOS RE package management, as well.

Is the plan to build most of it as part of the distribution itself (the way SerenityOS and Aero manage software and ravynOS plans to in the near future) or will it be more like the decentralized/the classic Debian or BSD ports approach?

**Comment by eadwardus** [comment]
Hello there! Glad you liked it : ]

> brief documentation

It has a minimal doc on:
https://eltaninos.org/en/download/tools/venus
https://eltaninos.org/en/download/tools/arbor

But it's true it needs a more detailed one, I still didn't because venus (the pm part of it) is basically redo rules, so I want to create an interface for it to provide the user a stable pm (so if I change the rules they won't necessarily affect the interface).

> how do I install `git`

Still missing from the official repos, but as I need to update the remote I'll do with it included, probably quite soon (ideally this week).

> is there already a remote repository of it somewhere

You can check if a package exists like this:

```
$ cd /venus-store
# redo repo/update
$ find repo -type f -name '${package-name}"
```
If it exists it can be installed like:
```
# redo programs/${package-name}
```

> Do I need to update Arbor and add it there myself?

In this case no, git surely will be added as part of the official repos. That said If a package does not exist it may need to be added locally, after doing so you can populate venus locally to be able to install it:

```
$ cd ${ARBOR-PATH}
$ ARBOR=$PWD bin/arbor ${package-name}
$ ARBOR=$PWD bin/arbor -p
$ myrepo="my-custom-local-repo"
# mkdir -p /venus-store/repo/${myrepo}
# bin/arbor -o /venus-store/repo/${myrepo}
```

> Will the final version maybe include some sort of compatibility shim for apt repositories?

Yes. As venus doesn't care much about the package format the idea is to add "modules" for it. At first to support natively pkgsrc which is ship together to complement the still small repos. Binary repositories can be added too but it might need isolation (for instance debian may have different lib versions from fedora, so mixing is not possible, also glacies uses musl instead of glibc), as if sub-systems. I'm still testing this locally though.

> Is the plan to build most of it as part of the distribution itself
> or will it be more like the decentralized

I would say both. The default repos are built like that, thought as part of the distribution, with patches and alternative deps (e.g netbsd curses, sortix zlib, libressl, etc.). However I do plan on creating a new repo for the community to collaborate (to provide additional packages, so not necessarily part of the distro itself, but still centralized in a way).

That said arbor can work completely decentralized too, one could create a clang glibc-repo using `/bin/bash` for the scripts and it would work just as the standard repos does, could even be used along with them (at the moment it cares about name-collision but I plan on fixing it next).

```
$ git clone https://git.eltaninos.org/arbor
$ cd arbor
$ ./bootstrap
$ (cd repo; git clone ${THIRD_PARTY_REPO_URI})
$ ARBOR=$PWD bin/arbor ${THIRD_PARTY_PACKAGE_NAME}
```

> intend making it my daily driver/help with its development once I have a new x86 based laptop.

Cool. Please join the communities, you can report anything through the mailing lists or the chat rooms (any will do they are bridged together), any doubt can contact me too in there.
https://eltaninos.org/en/community

**Comment by markusbkk** [comment]
Awesome! Thanks for the very insightful response.

When I ran the redo update command I actually realized I don't have any network connection inside the VM.
I chose "Shared network" inside UTM/QEMU so I assume it's not difficult and I just need to manually tinker with wpa_supplicant.

**Comment by eadwardus** [comment]
When using an virtual machine you can share the network as if it were an ethernet connection (even if your host machine uses wpa_supplicant or something of the like), doing so you can simply call `# dhcpcd eth0`

**Comment by markusbkk** [comment]
> When using an virtual machine you can share the network as if it were an ethernet connection (even if your host machine uses wpa_supplicant or something of the like), doing so you can simply call `# dhcpcd eth0`

Ah. Ok. It was THAT easy then. 
Got it. Thanks!

**Comment by eadwardus** [comment]
The site has been updated with relevant documentation for many things so closing the issue.
